# You are given a string s consisting only of letters 'a' and 'b'. 
# In a single step you can remove one palindromic subsequence from s.

# Return the minimum number of steps to make the given string empty.

# A string is a subsequence of a given string if it is generated by deleting some characters
# of a given string without changing its order. Note that a subsequence does not necessarily
# need to be contiguous.

# A string is called palindrome if is one that reads the same backward as well as forward.

 

# Example 1:

# Input: s = "ababa"
# Output: 1
# Explanation: s is already a palindrome, so its entirety can be removed in a single step.
# Example 2:

# Input: s = "abb"
# Output: 2
# Explanation: "abb" -> "bb" -> "". 
# Remove palindromic subsequence "a" then "bb".
# Example 3:

# Input: s = "baabb"
# Output: 2
# Explanation: "baabb" -> "b" -> "". 
# Remove palindromic subsequence "baab" then "b".
import operator

def removePalindromeSub(s):
    allpalindromes = []
    for i in range(len(s) - 1):
        end = len(s) - 1
        initial = i
        start = initial
        ending = 0
        while start < end:
            if s[start] == s[end]:
                ending = end
                while s[start] == s[end] and start < end:
                    start += 1
                    end -= 1
                if start >= end:
                    allpalindromes.append([initial, ending])
                else:
                    start = initial
            else:
                end -= 1
    reqPairs = []
    # if len(allpalindromes) == 1:
    #     return 1
    if len(allpalindromes) > 0:
        allpalindromes.sort(key=lambda inparr: inparr[0])
        reqPairs.append([0, 0])
        for pair in allpalindromes:
            if pair[0] <= reqPairs[-1][0]:
                if pair[1] - pair[0] > reqPairs[-1][1] - reqPairs[-1][0]:
                    reqPairs.pop()
                    reqPairs.append(pair)
            elif pair[0] > reqPairs[-1][1]:
                reqPairs.append(pair)
    initseq = reqPairs[0[0]] - 0
    for pair in reqPairs:
        initseq += pair[1] - pair[0]

print(removePalindromeSub('ababa'))
print(removePalindromeSub('abbaabbbbbbabaaabbb'))